name: Go

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.6

    - name: Build
      run: |
       go get 
       go build -v ./...

    - name: Test
      run: |
       go mod init github.com/kxchange/go-emojify
       go get
       go get -v github.com/stretchr/testify/assert
       go test -v ./...
